### ISSUE TITLE
Is this behaviour intended?

### ISSUE THREAD

**Issue by areebbeigh** [Simplistix/testfixtures#108]
When testfixtures is imported `unittest.mock` is accessible without having to explicitly `import unittest.mock`:

```python
import unittest
import sys

import testfixtures

class Test(unittest.TestCase):
    @unittest.mock.patch('sys.version_info', (2,7,0))
    def test_version(self):
        assert(sys.version_info < (3,0,0))
```

This should be throwing a `AttributeError: module 'unittest' has no attribute 'mock'` but importing testfixtures blocks this. 

Also, up to `testfixtures==3.0.2`, the above test fails as expected.

**Comment by cjw296** [comment]
I'm not sure why this would be, but what would you like to have happen?

**Comment by areebbeigh** [comment]
> I'm not sure why this would be, but what would you like to have happen?

`unittest.mock` shouldn't be in the global namespace because of `testfixtures` without it being imported explicitly. 

Here's an example of how this is potentially bad: https://github.com/coala/coala-bears/issues/2862

**Comment by cjw296** [comment]
`unittest.mock` isn't in the global namespace. `unittest.mock` is a module in the unittest package. Once a module has been imported anywhere in the python interpreter, it is available as an attribute of its containing package:

```
>>> import unittest
>>> unittest.mock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'unittest' has no attribute 'mock'
>>> def a_function():
...     import unittest.mock
... 
>>> a_function()
>>> unittest.mock
<module 'unittest.mock' from '.../unittest/mock.py'>
```
I tried to follow coala/coala-bears#2862 but, honestly, this looks like a lot of conjecture based around a lack of understanding around python. I don't know what `coalaBearTest.py` and the `coalaBearTest` class are supposed to represent, but the names alone suggest a [lack of familiarity with Python](https://www.python.org/dev/peps/pep-0008/#naming-conventions).

Now, importing `testfixtures` will import `unittest.mock` and the `mock` backport, if it's available, as part of providing comparison for `Mock` objects. I'd be surprised if any code should fail because a module that is present is imported. This certainly isn't "funky", and I doubt pytest is doing any "magic" in this area.

Just to check you're aware: `unittest.mock` does not exist in Python 2, it only exists in Python 3. If your code needs to use mock on both Python 2 and 3, then you'll need to conditionally rely on the `mock` backport, which will require different import statements.
