### ISSUE TITLE
No longer compatible with sybil==3.*

### ISSUE THREAD

**Issue by jonringer** [simplistix/testfixtures#169]
Tests fail:

```
error: builder for '/nix/store/x1x2xj9539pqydnqqc7syi4hqpvkm3wv-python3.9-testfixtures-6.18.3.drv' failed with exit code 4;
       last 10 log lines:
       > Executing pythonImportsCheckPhase
       > Check whether the following modules can be imported: testfixtures
       > pytestCheckPhase
       > Executing pytestCheckPhase
       > ImportError while loading conftest '/build/testfixtures-6.18.3/testfixtures/tests/conftest.py'.
       > testfixtures/tests/conftest.py:21: in <module>
       >     CodeBlockParser(),
       > /nix/store/zqhlwzm5nqg6fx04cvjbja0wm0dm0zm1-sybil-3.0.0/lib/python3.9/site-packages/sybil/parsers/codeblock.py:34: in __init__
       >     assert self.language, 'language must be specified!'
       > E   AttributeError: 'CodeBlockParser' object has no attribute 'language'
       For full logs, run 'nix log /nix/store/x1x2xj9539pqydnqqc7syi4hqpvkm3wv-python3.9-testfixtures-6.18.3.drv'.
```

**Comment by cjw296** [comment]
This cropped up in https://github.com/simplistix/testfixtures/pull/167 too.
Unfortunately, python packaging metadata has no way to express "if you have this package installed, it needs to match there version requirements". If you know better, please let me know!

What lead you to encounter this? Are you using sybil with testfixtures?

**Comment by jonringer** [comment]
> What lead you to encounter this? Are you using sybil with testfixtures?

I'm running the test suite of this package

```
       > testfixtures/tests/conftest.py:21: in <module>
       >     CodeBlockParser(),

**Comment by cjw296** [comment]
What lead you to run the test suite?
How are you setting up your development environment?

**Comment by cjw296** [comment]
So here's the thing: you're throwing out a "bug" report without doing even a basic amount of due diligence.

Had you bothered to look, you might have noticed:
- I'm the author of sybil. I'm also the author of testfixtures.
- The CI for both testfixtures and sybil is green, so rather than reporting a "bug", maybe consider what you're doing wrong.
- This is already accounted for on master, so seems fairly obvious to a packager like yourself that the correct solution here is to pin `sybil<3` until a new release of testfixtures is made.
- I've explained there's no way this can be expressed in a Python package's metadata.

With a bit more digging you may have even found https://github.com/cjw296/testfixtures/tree/v7.

Where this once again leaves me, as you'll see by looking at issues tagged with [linux-distro-packaging](https://github.com/simplistix/testfixtures/labels/linux-distro-packaging), is yet more of the precious little time I have to do open source development being wasted to dealing with spurious issues logged up "distro packagers.

Please do the work, don't expect me to.

**Comment by cjw296** [comment]
Wow, you could even be bothered to read the issue linked from your own "expression" :-/
For the record, [this](https://github.com/NixOS/nixpkgs/blob/177f00e779316c3100524ba7ee9bc5a4937fd92c/pkgs/development/python-modules/testfixtures/default.nix#L41-L52) is totally bogus.

**Comment by jonringer** [comment]
sorry if my short response are coming off as rude. Your package is just one of 4800 that we try to maintain. 

> This is already accounted for on master, so seems fairly obvious to a packager like yourself that the correct solution here is to pin sybil<3 until a new release of testfixtures is made.

We don't have that luxury. I mentioned earlier that we only have one version of a package, so we can't have sybil==2.x and sybil==3.x. 

> I've explained there's no way this can be expressed in a Python package's metadata.

I'm not sure what `this` means in this context

> With a bit more digging you may have even found https://github.com/cjw296/testfixtures/tree/v7.

I don't think a version control branch is regarded as proper python package management.

> Where this once again leaves me, as you'll see by looking at issues tagged with [linux-distro-packaging](https://github.com/simplistix/testfixtures/labels/linux-distro-packaging), is yet more of the precious little time I have to do open source development being wasted to dealing with spurious issues logged by "distro packagers.

I'll add a comment to not contact this upstream.

> Wow, you couldn't even be bothered to read the issue linked from your own "expression" :-/


The comment is a link to this bug report. It's to record that the upstream was made aware there's an issue with their released packages.

> For the record, [this](https://github.com/NixOS/nixpkgs/blob/177f00e779316c3100524ba7ee9bc5a4937fd92c/pkgs/development/python-modules/testfixtures/default.nix#L41-L52) is totally bogus.

Not all of them, at least `datetime` object are immutable, [according to cpython](https://docs.python.org/3/library/datetime.html).

**Comment by cjw296** [comment]
> Your package is just one of 4800 that we try to maintain.

How incredibly rude. "you're just a small cog, sorry we don't care".

**Comment by joepie91** [comment]
Hi, I just spoke to @jonringer, and I think that some sort of miscommunication happened here.

To clarify, their issue wasn't meant as a support request (in which case I could see why it'd come across as low-effort!), but rather just as a heads-up that something seemed broken on your end, in case you didn't know about it yet. On the NixOS side, there's already a solution in place, so there's really no rush for an upstream fix here.

So as I understand the situation, the frustration on *your* side seems to be because you felt like you were being asked to provide support without the necessary details, whereas the frustration on *their* side was because they thought they were being asked to do extra investigative work for something that was just supposed to be a heads-up.

I don't think that the intention of it being a heads-up was clear from their original post, though, so apologies for that. I won't bother you about this issue any further, I just want to try and clear the air; I know that the tension between packagers and maintainers can run high at times, and I don't think it's good for anybody involved for things to end in conflict :)

(Full disclosure: I'm not a packager myself, just a NixOS user and community member who cares about keeping the community healthy and friendly)

**Comment by cjw296** [comment]
"keeping the community healthy and friendly" - you're failing by continuing to **waste yet more of the precious little time I have to do open source development**.

To clarify, support or heads-up, issues like this are unhelpful and unwelcome. There's is nothing solvable or "broken" related to this issue in this package. Packaging spammers like @jonringer, @fabaff and @kloczek need to do better. If you're going to spam a package with your "issue", make very sure it's actually a problem.

Maybe a metaphor will help? 

"Hey, that bolt you give away for free..."

"Oh? This one that's carefully [measured each evening](https://app.circleci.com/pipelines/github/simplistix/testfixtures?branch=master) with [demonstrations of how it can be used with this nut](https://github.com/simplistix/testfixtures/blob/2900388a40c284c034f9714ee8fe58256d411453/testfixtures/tests/test_sybil.py) and when the nut changes size, [changes have to be made](https://github.com/simplistix/testfixtures/commit/2900388a40c284c034f9714ee8fe58256d411453)?"

"Yeah, we bashed it into the nut we had lying around with a hammer. The bolt broke."

"..."

"Your bolt is wrong and broken."

😳 "Don't do that..."

"No look, we bang, thousands of things that might be nails into stuff, 4,800 things no less, we've got a **great** hammer. We're being *helpful* by telling you this, why are you so ungrateful?!"

"Please go away."

"Hey, so you told my friend to go away, so here's the thing... when you bash this bolt of yours into the wrong size nut, you should be grateful that we make you listen to us complain about it not working".

🙄
