### ISSUE TITLE
OutputCapture.disable doesn't work from within interactive debugger 

### ISSUE THREAD

**Issue by wimglenn** [Simplistix/testfixtures#38]
Example:

```
Python 2.7.5 (default, Oct 11 2015, 17:47:16) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, pdb
>>> from testfixtures import OutputCapture
>>> with OutputCapture() as oc:
...     print 'first'
...     pdb.set_trace()
...     print 'fourth'
... 
oc.disable()  
print 'second'
print >> sys.__stdout__, 'third'
third
c
>>> oc.captured
'first\n> <stdin>(4)<module>()\n(Pdb) (Pdb) second\n(Pdb) (Pdb) fourth\n'

```

The line 'second' should not have been captured.

**Comment by cjw296** [comment]
Okay, so, to be clear, this doesn't happen when the `.disable()` is put in the source code...

**Comment by wimglenn** [comment]
Correct

**Comment by cjw296** [comment]
Right, so I'm pretty sure the problem is here:
https://hg.python.org/cpython/file/v2.7.12/Lib/pdb.py#l221

Not sure what the best solution is. `OutputCapture` could grow a `.pdb()` method, which basically did `Pdb(stdout=self.original_stdout).set_trace(sys._getframe().f_back)`, but that will only help people using pdb.

Also bear in mind that when looking into this, I hit nose's annoying 'capture output by default' behaviour, which also makes pdb sad. Indeed, it also make's PyCharm's debugger sad for the same reason!

The easiest thing might just be to add a note suggesting the following snippet when using an interactive debugger:

```python
import sys; sys.stdout=sys.__stdout__
```

Thoughts?

**Comment by wimglenn** [comment]
Certainly an acceptable solution.  Getting it to function properly in debuggers seems way more work than it's worth when there is an easy workaround.
