### ISSUE TITLE
testfixtures.__version__ doesn't exist

### ISSUE THREAD

**Issue by asqui** [Simplistix/testfixtures#94]
Is there any other easy way to see what version of the package you are using?

Should we add `__version__` to `__init__.py`, as is typically done for other packages?

**Comment by cjw296** [comment]
I what context are you looking to find the version?
```
$ python setup.py --version
6.3.0
```

That's the standard way, AFAIK.

**Comment by cjw296** [comment]
Also https://github.com/sdispater/poetry/issues/144#issuecomment-393257700

**Comment by asqui** [comment]
The context is I've got the module imported and want an easy way to double-check what version I'm running.

For example: https://github.com/zzzeek/sqlalchemy/blob/576b33d46a9418424e94926bf9f02bdad3fc593f/lib/sqlalchemy/__init__.py#L133

**Comment by cjw296** [comment]
Why do you want to check the module at import time? There's a `version.txt` inside the module you could look at, but I'm likely to switch testfixtures to poetry at some stage, in which case that file will go away..

**Comment by cjw296** [comment]
No followup in a couple of weeks, so let's close until  sdispater/poetry#144 takes care of this.

**Comment by fabiencelier** [comment]
Hello @cjw296 

According to [PEP 396](https://www.python.org/dev/peps/pep-0396/) it is a good practice to include the version of your package in a `__version__` variable.

This is useful if you want to check the module version at import time, for instance because different version have different API so you will do different calls.

Also there should be a single source of truth for both `__version__` and the version in setup.py, here it can be your "version.txt" which is perfect for that.

I'd be happy to make you a PR if you want !

**Comment by cjw296** [comment]
Sure, PR welcome :-)
